jdbc.default.driverClassName=org.postgresql.Driver
jdbc.default.url=jdbc:postgresql://db:5432/liferay
jdbc.default.username=liferay
jdbc.default.password=liferay

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

web.server.protocol=http
web.server.host=localhost
web.server.port=80

portal.proxy.enabled=true

redirect.url.security.mode=domain

module.framework.properties.osgi.console=11311
module.framework.properties.osgi.console.enabled=true